config/routes.rb
Rails.application.routes.draw do
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for @article do |f| %>
  <%= f.input :title %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <br><br>
  <%= f.submit class: "btn btn-success" %>
  <br><br>
  <% if @article.id %>
    <%= link_to "Show |", article_path(@article)  %>
  <% end %>
  <%= link_to "Back", articles_path  %>
<% end %>

app/views/articles/edit.html.erb
<div class="container d-flex justify-content-center">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <h2>Edit Article</h1>
        <%= render 'articles/form' %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container d-flex justify-content-center">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <% @articles.each do |article| %>
        <article>
          <h2>
            <%= link_to "#{article.title}",article_path(article) %>
          </h2>
            <%= article.content %>
        </article>
        <% end %>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container d-flex justify-content-center">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <h2>New Article</h1>
        <%= render 'articles/form' %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <article>
        <h1>
          <%= @article.title %>
          <small>
            <%= link_to "✏️" , edit_article_path(@article) %>
            <%= link_to "🚮️", article_path(@article), method: :delete, data: { confirm: "Are you sure?" }%>
          </small>
        </h1>
        <hr>
        <p><%= @article.content %></p>
      </article>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>